sudo: required
services:
 - docker

before_install:
 - docker build -t kunalchoudhary2/docker-react -f Dockerfile.dev .

script:
 - docker run -e "CI=true" kunalchoudhary2/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-west-1"
 app: "docker"	
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-us-west-1-977479030618"
 bucket_path: "docker"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY	
 secret_access_key:
  secure: "$AWS_SECRET_KEY"
